name: paper-to-podcast

services:
  p2p-server:
    build: .
    image: p2p-backend
    container_name: p2p-server
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - OPENAI_MODEL=gpt-4o-mini
    volumes:
      - ./output:/output/
      - ./pdfs:/pdfs/
